"use client";

import { useCurrentLanguageCode } from "@/features/i18n/translation-store";

type MarketingLabelKey =
  | "about"
  | "bookClinicDemo"
  | "bookDemo"
  | "contact"
  | "guidedPilot"
  | "howItWorks"
  | "humanReviewedAi"
  | "leadIntakeOnly"
  | "noMedicalRecords"
  | "sampleDashboard"
  | "support";

const localizedLabels: Record<MarketingLabelKey, Record<string, string>> = {
  about: {
    en: "About",
    uk: "Про нас",
    pl: "O nas",
    de: "Über uns",
    fr: "À propos",
    es: "Acerca de",
    it: "Chi siamo",
    "pt-BR": "Sobre",
    "pt-PT": "Sobre",
    nl: "Over ons",
    sv: "Om oss",
    no: "Om oss",
    da: "Om os",
    fi: "Tietoa",
    et: "Meist",
    lv: "Par mums",
    lt: "Apie mus",
    cs: "O nás",
    sk: "O nás",
    hu: "Rólunk",
    ro: "Despre",
    bg: "За нас",
    el: "Σχετικά",
    tr: "Hakkında",
    ar: "من نحن",
    he: "אודות",
    fa: "درباره",
    hi: "परिचय",
    ur: "تعارف",
    "zh-CN": "关于",
    "zh-TW": "關於",
    ja: "概要",
    ko: "소개",
    id: "Tentang",
    ms: "Tentang",
    th: "เกี่ยวกับ",
    vi: "Giới thiệu",
    fil: "Tungkol",
    sw: "Kuhusu",
  },
  bookDemo: {
    en: "Book demo",
    uk: "Запис на демо",
    pl: "Umów demo",
    de: "Demo buchen",
    fr: "Réserver une démo",
    es: "Reservar demo",
    it: "Prenota demo",
    "pt-BR": "Agendar demo",
    "pt-PT": "Marcar demo",
    nl: "Demo boeken",
    sv: "Boka demo",
    no: "Bestill demo",
    da: "Book demo",
    fi: "Varaa demo",
    et: "Broneeri demo",
    lv: "Rezervēt demo",
    lt: "Užsakyti demo",
    cs: "Rezervovat demo",
    sk: "Rezervovať demo",
    hu: "Demó foglalása",
    ro: "Programează demo",
    bg: "Резервирай демо",
    el: "Κλείστε demo",
    tr: "Demo ayırt",
    ar: "احجز عرضًا",
    he: "קבע הדגמה",
    fa: "رزرو دمو",
    hi: "डेमो बुक करें",
    ur: "ڈیمو بک کریں",
    "zh-CN": "预约演示",
    "zh-TW": "預約示範",
    ja: "デモ予約",
    ko: "데모 예약",
    id: "Pesan demo",
    ms: "Tempah demo",
    th: "จองเดโม",
    vi: "Đặt demo",
    fil: "Mag-book ng demo",
    sw: "Weka demo",
  },
  bookClinicDemo: {
    en: "Book 15-min clinic demo",
    uk: "Запис на 15-хв демо клініки",
    pl: "Umów 15-min demo kliniki",
    de: "15-Minuten-Klinikdemo buchen",
    fr: "Réserver une démo clinique de 15 min",
    es: "Reservar demo clínica de 15 min",
    it: "Prenota demo clinica di 15 min",
    "pt-BR": "Agendar demo clínica de 15 min",
    "pt-PT": "Marcar demo clínica de 15 min",
    nl: "Boek kliniekdemo van 15 min",
    sv: "Boka 15 min klinikdemo",
    no: "Bestill 15 min klinikkdemo",
    da: "Book 15 min klinikdemo",
    fi: "Varaa 15 min klinikkademo",
    et: "Broneeri 15 min kliinikudemo",
    lv: "Rezervēt 15 min klīnikas demo",
    lt: "Užsakyti 15 min klinikos demo",
    cs: "Rezervovat 15min demo kliniky",
    sk: "Rezervovať 15-min demo kliniky",
    hu: "15 perces klinikai demó foglalása",
    ro: "Programează demo clinică de 15 min",
    bg: "Резервирай 15-мин демо за клиника",
    el: "Κλείστε demo κλινικής 15 λεπτών",
    tr: "15 dk klinik demosu ayırt",
    ar: "احجز عرض عيادة لمدة 15 دقيقة",
    he: "קבע הדגמת מרפאה של 15 דקות",
    fa: "رزرو دمو ۱۵ دقیقه‌ای کلینیک",
    hi: "15-मिनट क्लिनिक डेमो बुक करें",
    ur: "15 منٹ کلینک ڈیمو بک کریں",
    "zh-CN": "预约15分钟诊所演示",
    "zh-TW": "預約15分鐘診所示範",
    ja: "15分のクリニックデモを予約",
    ko: "15분 클리닉 데모 예약",
    id: "Pesan demo klinik 15 menit",
    ms: "Tempah demo klinik 15 min",
    th: "จองเดโมคลินิก 15 นาที",
    vi: "Đặt demo phòng khám 15 phút",
    fil: "Mag-book ng 15-min clinic demo",
    sw: "Weka demo ya kliniki ya dakika 15",
  },
  contact: {
    en: "Contact",
    uk: "Контакти",
    pl: "Kontakt",
    de: "Kontakt",
    fr: "Contact",
    es: "Contacto",
    it: "Contatto",
    "pt-BR": "Contato",
    "pt-PT": "Contacto",
    nl: "Contact",
    sv: "Kontakt",
    no: "Kontakt",
    da: "Kontakt",
    fi: "Yhteys",
    et: "Kontakt",
    lv: "Kontakti",
    lt: "Kontaktai",
    cs: "Kontakt",
    sk: "Kontakt",
    hu: "Kapcsolat",
    ro: "Contact",
    bg: "Контакт",
    el: "Επικοινωνία",
    tr: "İletişim",
    ar: "تواصل",
    he: "יצירת קשר",
    fa: "تماس",
    hi: "संपर्क",
    ur: "رابطہ",
    "zh-CN": "联系",
    "zh-TW": "聯絡",
    ja: "連絡先",
    ko: "문의",
    id: "Kontak",
    ms: "Hubungi",
    th: "ติดต่อ",
    vi: "Liên hệ",
    fil: "Makipag-ugnayan",
    sw: "Mawasiliano",
  },
  guidedPilot: {
    en: "Guided pilot available",
    uk: "Доступний керований пілот",
    pl: "Dostępny pilotaż z pomocą",
    de: "Geführter Pilot verfügbar",
    fr: "Pilote accompagné disponible",
    es: "Piloto guiado disponible",
    it: "Pilot guidato disponibile",
    "pt-BR": "Piloto guiado disponível",
    "pt-PT": "Piloto guiado disponível",
    nl: "Begeleide pilot beschikbaar",
    sv: "Guidad pilot tillgänglig",
    no: "Veiledet pilot tilgjengelig",
    da: "Guidet pilot tilgængelig",
    fi: "Ohjattu pilotti saatavilla",
    et: "Juhendatud piloot saadaval",
    lv: "Pieejams vadīts pilots",
    lt: "Galimas vedamas pilotas",
    cs: "Řízený pilot k dispozici",
    sk: "Riadený pilot k dispozícii",
    hu: "Irányított pilot elérhető",
    ro: "Pilot ghidat disponibil",
    bg: "Наличен е воден пилот",
    el: "Διαθέσιμο καθοδηγούμενο πιλοτικό πρόγραμμα",
    tr: "Rehberli pilot mevcut",
    ar: "يتوفر تشغيل تجريبي موجه",
    he: "פיילוט מודרך זמין",
    fa: "پایلوت راهنمایی‌شده در دسترس است",
    hi: "मार्गदर्शित पायलट उपलब्ध",
    ur: "رہنمائی شدہ پائلٹ دستیاب ہے",
    "zh-CN": "可提供引导式试点",
    "zh-TW": "可提供引導式試點",
    ja: "ガイド付きパイロット利用可",
    ko: "가이드 파일럿 제공",
    id: "Pilot terpandu tersedia",
    ms: "Pilot berpandu tersedia",
    th: "มีช่วงทดลองแบบมีคำแนะนำ",
    vi: "Có pilot có hướng dẫn",
    fil: "May guided pilot",
    sw: "Majaribio yanayoongozwa yanapatikana",
  },
  howItWorks: {
    en: "How it works",
    uk: "Як працює",
    pl: "Jak działa",
    de: "So funktioniert es",
    fr: "Fonctionnement",
    es: "Cómo funciona",
    it: "Come funziona",
    "pt-BR": "Como funciona",
    "pt-PT": "Como funciona",
    nl: "Hoe het werkt",
    sv: "Så fungerar det",
    no: "Slik fungerer det",
    da: "Sådan virker det",
    fi: "Näin se toimii",
    et: "Kuidas see toimib",
    lv: "Kā tas darbojas",
    lt: "Kaip tai veikia",
    cs: "Jak to funguje",
    sk: "Ako to funguje",
    hu: "Hogyan működik",
    ro: "Cum funcționează",
    bg: "Как работи",
    el: "Πώς λειτουργεί",
    tr: "Nasıl çalışır",
    ar: "كيف يعمل",
    he: "איך זה עובד",
    fa: "نحوه کار",
    hi: "यह कैसे काम करता है",
    ur: "یہ کیسے کام کرتا ہے",
    "zh-CN": "工作方式",
    "zh-TW": "運作方式",
    ja: "仕組み",
    ko: "작동 방식",
    id: "Cara kerja",
    ms: "Cara ia berfungsi",
    th: "วิธีทำงาน",
    vi: "Cách hoạt động",
    fil: "Paano ito gumagana",
    sw: "Jinsi inavyofanya kazi",
  },
  humanReviewedAi: {
    en: "Human-reviewed AI drafts",
    uk: "AI-чернетки перевіряє команда",
    pl: "Szkice AI sprawdzane przez ludzi",
    de: "KI-Entwürfe mit menschlicher Prüfung",
    fr: "Brouillons IA relus par l'équipe",
    es: "Borradores de IA revisados por personas",
    it: "Bozze AI revisionate dal team",
    "pt-BR": "Rascunhos de IA revisados por pessoas",
    "pt-PT": "Rascunhos de IA revistos por pessoas",
    nl: "AI-concepten met menselijke review",
    sv: "AI-utkast granskas av människor",
    no: "AI-utkast gjennomgås av mennesker",
    da: "AI-kladder gennemgås af mennesker",
    fi: "Ihmisen tarkistamat AI-luonnokset",
    et: "Inimese üle vaadatud AI-mustandid",
    lv: "Cilvēka pārskatīti AI melnraksti",
    lt: "Žmogaus peržiūrimi AI juodraščiai",
    cs: "AI návrhy kontrolované člověkem",
    sk: "AI návrhy kontrolované človekom",
    hu: "Ember által ellenőrzött AI-vázlatok",
    ro: "Ciorne AI verificate de oameni",
    bg: "AI чернови, преглеждани от човек",
    el: "Προσχέδια AI με ανθρώπινο έλεγχο",
    tr: "İnsan onaylı AI taslakları",
    ar: "مسودات ذكاء اصطناعي يراجعها الفريق",
    he: "טיוטות AI בבדיקה אנושית",
    fa: "پیش‌نویس‌های AI با بازبینی انسانی",
    hi: "मानव-समीक्षित AI ड्राफ्ट",
    ur: "انسانی جائزے والے AI مسودے",
    "zh-CN": "人工审核的 AI 草稿",
    "zh-TW": "人工審核的 AI 草稿",
    ja: "人が確認するAI下書き",
    ko: "사람이 검토하는 AI 초안",
    id: "Draf AI ditinjau manusia",
    ms: "Draf AI disemak manusia",
    th: "ร่าง AI ที่ทีมตรวจสอบ",
    vi: "Bản nháp AI do người duyệt",
    fil: "AI draft na sinusuri ng tao",
    sw: "Rasimu za AI hupitiwa na binadamu",
  },
  leadIntakeOnly: {
    en: "Lead intake only",
    uk: "Лише обробка звернень",
    pl: "Tylko obsługa zgłoszeń",
    de: "Nur Lead-Aufnahme",
    fr: "Intake de leads uniquement",
    es: "Solo entrada de leads",
    it: "Solo acquisizione lead",
    "pt-BR": "Somente entrada de leads",
    "pt-PT": "Apenas entrada de leads",
    nl: "Alleen lead-intake",
    sv: "Endast leadintag",
    no: "Kun lead-inntak",
    da: "Kun lead-indtag",
    fi: "Vain liidien vastaanotto",
    et: "Ainult päringute vastuvõtt",
    lv: "Tikai pieprasījumu uzņemšana",
    lt: "Tik užklausų priėmimas",
    cs: "Pouze příjem poptávek",
    sk: "Iba príjem dopytov",
    hu: "Csak lead-fogadás",
    ro: "Doar preluare de lead-uri",
    bg: "Само приемане на запитвания",
    el: "Μόνο λήψη leads",
    tr: "Yalnızca lead kabulü",
    ar: "استقبال العملاء المحتملين فقط",
    he: "קליטת לידים בלבד",
    fa: "فقط دریافت سرنخ‌ها",
    hi: "केवल लीड इनटेक",
    ur: "صرف لیڈ انٹیک",
    "zh-CN": "仅用于线索接收",
    "zh-TW": "僅用於名單接收",
    ja: "リード受付のみ",
    ko: "리드 접수 전용",
    id: "Hanya intake prospek",
    ms: "Intake lead sahaja",
    th: "รับลีดเท่านั้น",
    vi: "Chỉ tiếp nhận lead",
    fil: "Lead intake lang",
    sw: "Upokeaji wa leads pekee",
  },
  noMedicalRecords: {
    en: "No medical records required",
    uk: "Медичні записи не потрібні",
    pl: "Bez wymaganych dokumentacji medycznych",
    de: "Keine Patientenakten erforderlich",
    fr: "Aucun dossier médical requis",
    es: "No requiere historias clínicas",
    it: "Nessuna cartella clinica richiesta",
    "pt-BR": "Sem prontuários médicos necessários",
    "pt-PT": "Sem registos médicos necessários",
    nl: "Geen medische dossiers nodig",
    sv: "Inga journaler krävs",
    no: "Ingen journalføring kreves",
    da: "Ingen journaler kræves",
    fi: "Ei potilaskertomuksia tarvita",
    et: "Meditsiinilisi andmeid pole vaja",
    lv: "Medicīniskie ieraksti nav vajadzīgi",
    lt: "Medicininiai įrašai nereikalingi",
    cs: "Bez nutnosti zdravotních záznamů",
    sk: "Bez potreby zdravotných záznamov",
    hu: "Nincs szükség orvosi kartonokra",
    ro: "Nu sunt necesare fișe medicale",
    bg: "Не са нужни медицински досиета",
    el: "Δεν απαιτούνται ιατρικά αρχεία",
    tr: "Tıbbi kayıt gerekmez",
    ar: "لا حاجة إلى سجلات طبية",
    he: "אין צורך ברשומות רפואיות",
    fa: "نیازی به پرونده پزشکی نیست",
    hi: "मेडिकल रिकॉर्ड आवश्यक नहीं",
    ur: "طبی ریکارڈ درکار نہیں",
    "zh-CN": "不需要病历",
    "zh-TW": "不需要病歷",
    ja: "医療記録は不要",
    ko: "의료 기록 불필요",
    id: "Tidak perlu rekam medis",
    ms: "Rekod perubatan tidak diperlukan",
    th: "ไม่ต้องใช้เวชระเบียน",
    vi: "Không cần hồ sơ y tế",
    fil: "Hindi kailangan ang medical records",
    sw: "Hakuna rekodi za matibabu zinazohitajika",
  },
  sampleDashboard: {
    en: "Try sample dashboard",
    uk: "Демо-дашборд",
    pl: "Panel demo",
    de: "Beispiel-Dashboard",
    fr: "Tableau démo",
    es: "Panel de muestra",
    it: "Dashboard demo",
    "pt-BR": "Painel de exemplo",
    "pt-PT": "Painel de exemplo",
    nl: "Voorbeelddashboard",
    sv: "Exempelpanel",
    no: "Eksempelpanel",
    da: "Eksempelpanel",
    fi: "Esimerkkipaneeli",
    et: "Näidispaneel",
    lv: "Parauga panelis",
    lt: "Pavyzdinis skydelis",
    cs: "Ukázkový panel",
    sk: "Ukážkový panel",
    hu: "Minta irányítópult",
    ro: "Panou demo",
    bg: "Примерно табло",
    el: "Πίνακας demo",
    tr: "Örnek panel",
    ar: "لوحة تجريبية",
    he: "לוח דוגמה",
    fa: "داشبورد نمونه",
    hi: "नमूना डैशबोर्ड",
    ur: "نمونہ ڈیش بورڈ",
    "zh-CN": "示例看板",
    "zh-TW": "範例儀表板",
    ja: "サンプル画面",
    ko: "샘플 대시보드",
    id: "Dasbor contoh",
    ms: "Papan pemuka contoh",
    th: "แดชบอร์ดตัวอย่าง",
    vi: "Bảng mẫu",
    fil: "Sample dashboard",
    sw: "Dashibodi ya mfano",
  },
  support: {
    en: "Support",
    uk: "Підтримка",
    pl: "Wsparcie",
    de: "Support",
    fr: "Assistance",
    es: "Soporte",
    it: "Supporto",
    "pt-BR": "Suporte",
    "pt-PT": "Suporte",
    nl: "Support",
    sv: "Support",
    no: "Støtte",
    da: "Support",
    fi: "Tuki",
    et: "Tugi",
    lv: "Atbalsts",
    lt: "Pagalba",
    cs: "Podpora",
    sk: "Podpora",
    hu: "Támogatás",
    ro: "Suport",
    bg: "Поддръжка",
    el: "Υποστήριξη",
    tr: "Destek",
    ar: "الدعم",
    he: "תמיכה",
    fa: "پشتیبانی",
    hi: "सहायता",
    ur: "سپورٹ",
    "zh-CN": "支持",
    "zh-TW": "支援",
    ja: "サポート",
    ko: "지원",
    id: "Dukungan",
    ms: "Sokongan",
    th: "สนับสนุน",
    vi: "Hỗ trợ",
    fil: "Suporta",
    sw: "Usaidizi",
  },
};

function resolveLanguage(code: string): string {
  if (localizedLabels.about[code]) {
    return code;
  }

  const baseCode = code.split("-")[0] ?? "en";
  return localizedLabels.about[baseCode] ? baseCode : "en";
}

export function MarketingLocalizedText({
  className,
  fallback,
  k,
}: {
  className?: string;
  fallback?: string;
  k: MarketingLabelKey;
}) {
  const languageCode = useCurrentLanguageCode();
  const normalized = resolveLanguage(languageCode);

  return (
    <span className={className} suppressHydrationWarning>
      {localizedLabels[k][normalized] ?? fallback ?? localizedLabels[k].en}
    </span>
  );
}
